-J--no-fallback
-J--initialize-at-build-time=org.slf4j
-J--enable-url-protocols=http,https
-J-H:+ReportExceptionStackTraces
-J--strict-image-info
-J-H:+AddAllCharsets
-J-H:IncludeResourceBundles=org.sqlite.locale
