apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-db-pvc
  namespace: investment-portfolio-manager
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
