/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/assets/<id>": {
    delete: operations["delete_asset"];
  };
  "/api/portfolios/": {
    get: operations["list_portfolios"];
    post: operations["create_portfolio"];
  };
  "/api/portfolios/<id>": {
    get: operations["get_portfolio"];
    delete: operations["delete_portfolio"];
  };
  "/api/portfolios/<id>/performance": {
    get: operations["get_portfolio_performance"];
  };
  "/api/portfolios/<id>/tax-summary": {
    get: operations["get_portfolio_tax_summary"];
  };
  "/api/portfolios/<portfolio_id>/assets": {
    post: operations["create_asset"];
  };
  "/api/portfolios/<portfolio_id>/assets/<asset_id>/transactions": {
    post: operations["create_transaction"];
  };
  "/api/portfolios/<portfolio_id>/transactions": {
    get: operations["list_portfolio_transactions"];
  };
  "/api/transactions/<id>": {
    delete: operations["delete_transaction"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Asset: {
      asset_type: string;
      currency: string;
      /** Format: int32 */
      id: number;
      name: string;
      /** Format: int32 */
      portfolio_id: number;
      sector?: string | null;
      symbol: string;
    };
    AssetCreate: {
      asset_type: string;
      name: string;
      sector?: string | null;
      symbol: string;
    };
    AssetOut: {
      asset_type: string;
      /** Format: int32 */
      id: number;
      name: string;
      /** Format: int32 */
      portfolio_id: number;
      sector?: string | null;
      symbol: string;
      transactions: components["schemas"]["TransactionOut"][];
    };
    AssetTaxSummary: {
      asset_type: string;
      /** Format: double */
      average_cost: number;
      /** Format: double */
      current_price: number;
      /** Format: double */
      current_shares: number;
      /** Format: double */
      market_value: number;
      /** Format: double */
      realized_pnl: number;
      symbol: string;
      tax_lots: components["schemas"]["TaxLot"][];
      /** Format: double */
      total_cost: number;
      /** Format: double */
      unrealized_pnl: number;
      /** Format: double */
      unrealized_roi: number;
    };
    Portfolio: {
      base_currency: string;
      currency: string;
      description?: string | null;
      /** Format: int32 */
      id: number;
      name: string;
    };
    PortfolioCreate: {
      currency: string;
      description?: string | null;
      name: string;
    };
    PortfolioOut: {
      assets: components["schemas"]["AssetOut"][];
      currency: string;
      description?: string | null;
      /** Format: int32 */
      id: number;
      name: string;
    };
    TaxLot: {
      buy_date: components["schemas"]["DateTime"];
      /** Format: double */
      buy_price: number;
      /** Format: double */
      latent_gain_loss: number;
      /** Format: double */
      latent_roi: number;
      /** Format: double */
      original_qty: number;
      /** Format: double */
      remaining_qty: number;
    };
    Transaction: {
      /** Format: int32 */
      asset_id: number;
      date: components["schemas"]["DateTime"];
      /** Format: double */
      fee: number;
      /** Format: int32 */
      id: number;
      /** Format: double */
      price: number;
      /** Format: double */
      quantity: number;
      type: string;
    };
    TransactionCreate: {
      date: components["schemas"]["DateTime"];
      /** Format: double */
      fee: number;
      /** Format: double */
      price: number;
      /** Format: double */
      quantity: number;
      type: string;
    };
    TransactionOut: {
      /** Format: int32 */
      asset_id: number;
      date: components["schemas"]["DateTime"];
      /** Format: double */
      fee: number;
      /** Format: int32 */
      id: number;
      /** Format: double */
      price: number;
      /** Format: double */
      quantity: number;
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  delete_asset: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Asset deleted */
      204: {
        content: never;
      };
      /** @description Asset not found */
      404: {
        content: never;
      };
    };
  };
  list_portfolios: {
    responses: {
      /** @description List of portfolios */
      200: {
        content: {
          "application/json": components["schemas"]["PortfolioOut"][];
        };
      };
    };
  };
  create_portfolio: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["PortfolioCreate"];
      };
    };
    responses: {
      /** @description Portfolio created */
      201: {
        content: {
          "application/json": components["schemas"]["PortfolioOut"];
        };
      };
      /** @description Bad request */
      400: {
        content: never;
      };
    };
  };
  get_portfolio: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Portfolio found */
      200: {
        content: {
          "application/json": components["schemas"]["PortfolioOut"];
        };
      };
      /** @description Portfolio not found */
      404: {
        content: never;
      };
    };
  };
  delete_portfolio: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Portfolio deleted */
      204: {
        content: never;
      };
      /** @description Portfolio not found */
      404: {
        content: never;
      };
    };
  };
  get_portfolio_performance: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Performance data retrieved */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Portfolio not found */
      404: {
        content: never;
      };
    };
  };
  get_portfolio_tax_summary: {
    parameters: {
      query?: {
        strategy?: string | null;
        threshold_days?: number | null;
      };
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Tax summary retrieved */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Portfolio not found */
      404: {
        content: never;
      };
    };
  };
  create_asset: {
    parameters: {
      path: {
        portfolio_id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AssetCreate"];
      };
    };
    responses: {
      /** @description Asset created */
      201: {
        content: {
          "application/json": components["schemas"]["AssetOut"];
        };
      };
      /** @description Asset already exists */
      400: {
        content: never;
      };
      /** @description Portfolio not found */
      404: {
        content: never;
      };
    };
  };
  create_transaction: {
    parameters: {
      path: {
        asset_id: number;
        portfolio_id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TransactionCreate"];
      };
    };
    responses: {
      /** @description Transaction created */
      201: {
        content: {
          "application/json": components["schemas"]["TransactionOut"];
        };
      };
      /** @description Asset not found */
      404: {
        content: never;
      };
    };
  };
  list_portfolio_transactions: {
    parameters: {
      path: {
        portfolio_id: number;
      };
    };
    responses: {
      /** @description List of transactions */
      200: {
        content: {
          "application/json": components["schemas"]["TransactionOut"][];
        };
      };
      /** @description Portfolio not found */
      404: {
        content: never;
      };
    };
  };
  delete_transaction: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Transaction deleted */
      204: {
        content: never;
      };
      /** @description Transaction not found */
      404: {
        content: never;
      };
    };
  };
}
