/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/assets/<id>": {
    delete: operations["delete_asset"];
  };
  "/api/assets/lookup": {
    get: operations["lookup_isin"];
  };
  "/api/portfolios/": {
    get: operations["list_portfolios"];
    post: operations["create_portfolio"];
  };
  "/api/portfolios/<id>": {
    get: operations["get_portfolio"];
    delete: operations["delete_portfolio"];
    patch: operations["update_portfolio"];
  };
  "/api/portfolios/<id>/performance": {
    get: operations["get_portfolio_performance"];
  };
  "/api/portfolios/<id>/tax-summary": {
    get: operations["get_portfolio_tax_summary"];
  };
  "/api/portfolios/<portfolio_id>/assets": {
    post: operations["create_asset"];
  };
  "/api/portfolios/<portfolio_id>/assets/<asset_id>/transactions": {
    post: operations["create_transaction"];
  };
  "/api/portfolios/<portfolio_id>/transactions": {
    get: operations["list_portfolio_transactions"];
  };
  "/api/transactions/<id>": {
    delete: operations["delete_transaction"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Asset: {
      asset_type: string;
      currency: string;
      /** Format: int32 */
      id: number;
      isin?: string | null;
      name: string;
      /** Format: int32 */
      portfolio_id: number;
      sector?: string | null;
      symbol: string;
    };
    AssetCreate: {
      asset_type: string;
      currency: string;
      isin?: string;
      name: string;
      sector?: string | null;
      symbol: string;
    };
    AssetLookupResult: {
      asset_type: string;
      name: string;
      symbol: string;
    };
    AssetOut: {
      asset_type: string;
      currency: string;
      /** Format: int32 */
      id: number;
      isin?: string | null;
      name: string;
      /** Format: int32 */
      portfolio_id: number;
      sector?: string | null;
      symbol: string;
      transactions: components["schemas"]["TransactionOut"][];
    };
    AssetTaxSummary: {
      asset_type: string;
      average_cost: string;
      current_price: string;
      current_shares: string;
      market_value: string;
      realized_pnl: string;
      symbol: string;
      tax_lots: components["schemas"]["TaxLot"][];
      total_cost: string;
      unrealized_pnl: string;
      unrealized_roi: string;
    };
    Portfolio: {
      base_currency: string;
      currency: string;
      description?: string | null;
      /** Format: int32 */
      id: number;
      name: string;
    };
    PortfolioCreate: {
      currency: string;
      description?: string | null;
      name: string;
    };
    PortfolioOut: {
      assets: components["schemas"]["AssetOut"][];
      currency: string;
      description?: string | null;
      /** Format: int32 */
      id: number;
      name: string;
    };
    PortfolioUpdate: {
      currency: string;
    };
    TaxLot: {
      /** Format: date-time */
      buy_date: string;
      buy_price: string;
      latent_gain_loss: string;
      latent_roi: string;
      original_qty: string;
      remaining_qty: string;
    };
    Transaction: {
      /** Format: int32 */
      asset_id: number;
      /** Format: date-time */
      date: string;
      fee: string;
      /** Format: int32 */
      id: number;
      price: string;
      quantity: string;
      type: string;
    };
    TransactionCreate: {
      /** Format: date-time */
      date: string;
      fee: string;
      price: string;
      quantity: string;
      type: string;
    };
    TransactionOut: {
      /** Format: int32 */
      asset_id: number;
      /** Format: date-time */
      date: string;
      fee: string;
      /** Format: int32 */
      id: number;
      price: string;
      quantity: string;
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  delete_asset: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Asset deleted */
      204: {
        content: never;
      };
      /** @description Asset not found */
      404: {
        content: never;
      };
    };
  };
  lookup_isin: {
    parameters: {
      query: {
        /** @description ISIN to look up (12 alphanumeric characters) */
        isin: string;
      };
    };
    responses: {
      /** @description Asset metadata resolved from ISIN */
      200: {
        content: {
          "application/json": components["schemas"]["AssetLookupResult"];
        };
      };
      /** @description Invalid ISIN format */
      400: {
        content: never;
      };
      /** @description ISIN not found */
      404: {
        content: never;
      };
    };
  };
  list_portfolios: {
    responses: {
      /** @description List of portfolios */
      200: {
        content: {
          "application/json": components["schemas"]["PortfolioOut"][];
        };
      };
    };
  };
  create_portfolio: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["PortfolioCreate"];
      };
    };
    responses: {
      /** @description Portfolio created */
      201: {
        content: {
          "application/json": components["schemas"]["PortfolioOut"];
        };
      };
      /** @description Bad request */
      400: {
        content: never;
      };
    };
  };
  get_portfolio: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Portfolio found */
      200: {
        content: {
          "application/json": components["schemas"]["PortfolioOut"];
        };
      };
      /** @description Portfolio not found */
      404: {
        content: never;
      };
    };
  };
  delete_portfolio: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Portfolio deleted */
      204: {
        content: never;
      };
      /** @description Portfolio not found */
      404: {
        content: never;
      };
    };
  };
  update_portfolio: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PortfolioUpdate"];
      };
    };
    responses: {
      /** @description Portfolio updated */
      200: {
        content: {
          "application/json": components["schemas"]["PortfolioOut"];
        };
      };
      /** @description Portfolio not found */
      404: {
        content: never;
      };
    };
  };
  get_portfolio_performance: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Performance data retrieved */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Portfolio not found */
      404: {
        content: never;
      };
    };
  };
  get_portfolio_tax_summary: {
    parameters: {
      query?: {
        strategy?: string | null;
        threshold_days?: number | null;
      };
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Tax summary retrieved */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Portfolio not found */
      404: {
        content: never;
      };
    };
  };
  create_asset: {
    parameters: {
      path: {
        portfolio_id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AssetCreate"];
      };
    };
    responses: {
      /** @description Asset created */
      201: {
        content: {
          "application/json": components["schemas"]["AssetOut"];
        };
      };
      /** @description Asset already exists */
      400: {
        content: never;
      };
      /** @description Portfolio not found */
      404: {
        content: never;
      };
    };
  };
  create_transaction: {
    parameters: {
      path: {
        asset_id: number;
        portfolio_id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TransactionCreate"];
      };
    };
    responses: {
      /** @description Transaction created */
      201: {
        content: {
          "application/json": components["schemas"]["TransactionOut"];
        };
      };
      /** @description Asset not found */
      404: {
        content: never;
      };
    };
  };
  list_portfolio_transactions: {
    parameters: {
      path: {
        portfolio_id: number;
      };
    };
    responses: {
      /** @description List of transactions */
      200: {
        content: {
          "application/json": components["schemas"]["TransactionOut"][];
        };
      };
      /** @description Portfolio not found */
      404: {
        content: never;
      };
    };
  };
  delete_transaction: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description Transaction deleted */
      204: {
        content: never;
      };
      /** @description Transaction not found */
      404: {
        content: never;
      };
    };
  };
}
